# NOT FOR FLORIS, just for environmental setup

wind_speed:
  min: 4.0
  max: 14.0

wind_direction:
  min: 250.0
  max: 290.0

yaw:
  min: -25.0
  max: 25.0

turbulence_intensity:
  fixed: 0.06   # or use min/max if you want randomization later

num_turbines:
  fixed: 3