name: "simple_farm"
description: "Minimal FLORIS v4.5 config for data generation"
floris_version: "4.5"

logging:
  console:
    enable: false

solver:
  type: turbine_grid

wake:
  model_strings:
    velocity_model: "gauss"          # will be overridden in Python per model
    deflection_model: "gauss"
    turbulence_model: "crespo_hernandez"
    wake_combination_model: "sosfs"
    partial_wake_model: "auto"
  enable_secondary_steering: false
  enable_yaw_added_recovery: false
  enable_transverse_velocities: false
  enable_active_wake_mixing: false
  wake_deflection_parameters: {}
  wake_turbulence_parameters: {}


flow_field:
  air_density: 1.225
  wind_speeds: [8.0]                 # will be overwritten by fm.set(...)
  wind_directions: [270.0]
  turbulence_intensities: [0.06]

farm:
  layout_x: [0.0]                    # will be overwritten dynamically
  layout_y: [0.0]
  turbine_type: ["iea37-10mw"]
